config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only: [:index , :show] do
    resources :comments, only: [:destroy, :create]
  end
  resources :users, only: [:index, :show] do
    resources :follows, only: [:create]
  end

  resources :requests, only: [:create, :index]
  resources :listed_books, only: [:create, :update]
  resources :recommendations, only: [:create]

  #get 'books/:asin', to: 'books#show'
  delete 'follows', to: 'follows#destroy', as: 'user_follow'
  #post 'books/comments/:asin', to: 'comments#create', as: 'books_comment'
  delete 'requests', to: 'requests#destroy', as: 'request_delete'
  delete 'recommendations', to: 'recommendations#destroy', as: 'recommendation_delete'
  root 'books#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments, dependent: :destroy
  has_many :books, through: :listed_books
  has_many :listed_books, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :followees, through: :follows
  has_many :requests, dependent: :destroy
  has_many :recommendations, dependent: :destroy
  #has_many :recipients, through: :requests
  has_many :inverse_requests, class_name: 'Request', foreign_key: 'recipient_id', dependent: :destroy
  has_many :inverse_recommendations, class_name: 'Recommendation', foreign_key: 'recipient_id', dependent: :destroy
  paginates_per 10

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }, :presence => true


  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.search(search)
    if search.present?
      users = []
      users += User.where('email ILIKE ?', search).to_a
      users += User.where('username ILIKE ?', search).to_a
      users
    else
      []
    end
  end

  def does_not_have(book)
    !self.books.map(&:asin).include?(book.asin)
  end

  def requested_user?(user)
    self.requests.map(&:recipient).include?(user)
  end

  def is_following?(user)
    self.follows.find_by(followee: user).present?
  end

  #Only mutual follows may recommend books to each other.
  def mutual_follows
    self.followees.to_a.select { |followee| followee.is_following?(self) }
  end

  def has_recommended?(book, user)
    self.recommendations.find_by(book: book, recipient: user).present?
  end

  def books_with_recommendations(is_read: is_read)

    #get all the users books that they've read
    books = self.listed_books.where(is_read: is_read).order(:order_index).to_a.map(&:book)
    recs = {}
    #Each book has a list of users that they are **allowed** to recommend the book to.
    books.each do |book|
      recs[book] = self.mutual_follows.to_a.select { |follow| follow.does_not_have(book) && !self.has_recommended?(book, follow) }
    end
    recs
  end

  def listed_book_from_book(book)
    self.listed_books.find_by(book: book)
  end

  def last_listed_book?(listed_book)
    listed_book.order_index ==
      self.listed_books.where(is_read: listed_book.is_read).map(&:order_index).max
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    unless params[:only_follow]
      @users = User.search(params[:search_user])
      if !@users.present? && params[:search_user].present?

        flash[:alert] = "Your search did not match any users. Please try again."
      end
    else
      @users = current_user.followees
    end
  end

  def show
    @user = User.find(params[:id])
    @comment = Comment.new
    @user_read_books = @user.books_with_recommendations(is_read: true)
    @user_unread_books = @user.books_with_recommendations(is_read: false)
  end
end

app/views/users/_user.html.erb
<div class="row user">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-body">
       <%= link_to user.username + ' ' + user.email, user_path(user) %>

        <% if user_signed_in? && !current_user.followees.include?(user) %>
          <%= button_to "Follow", user_follows_path(user), class: "btn btn-primary pull-right" %>
          <%= button_to("Ignore", request_delete_path(user_id: user.id, recipient_id: current_user.id), method: :delete, class: "btn btn-danger pull-right") if user.requested_user?(current_user) %>
        <% elsif user_signed_in? && current_user != user %>
           <%= button_to "Following", user_follows_path(user), disabled: "disabled", class: "btn btn-success pull-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user_book.html.erb
<div class="row book">
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="col-md-2">
        <%= image_tag(user_book.photo, class: "img-responsive", alt: "Responsive image") %>
      </div>
      <div class="col-md-6">
        <h4> <%= link_to user_book.title, "/books/#{user_book.asin}" %> </h4> <br>
        <h5>By: <%= user_book.authors.map(&:name).join(', ') %> </h5><br>
        <% if (@comment = user_book.most_recent_comment(current_user)).present? %>
          <%= @comment.content %> says <%= @comment.user.username %>
        <% end %>
      </div>
      <div class="col-md-3">
        <% if user_signed_in? && current_user.does_not_have(user_book) %>
          <%= button_to "Add to MyReads", listed_books_path(asin: user_book.asin), class: "btn btn-default" %>

        <% elsif user_signed_in? && user == current_user %>
          <% unless (@display_div = (recommendables.count == 0)) %> <div class="btn-group"> <% end %>
            <%= link_to "Mark as unread", listed_book_path(current_user.listed_book_from_book(user_book), is_read: false), method: :patch, class: 'btn btn-default' if has_read %>
            <%unless has_read%><a href="#test-popup" class="open-popup-link btn btn-default">Mark as read</a><%end%>
            <% if recommendables.count > 0 %>
              <div class="btn-group pull-right">
                <a class="btn btn-default dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown">
                Recommend:
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">

                <% recommendables.each do |recommendable| %>
                  <li role="presentation"><%= link_to(recommendable.username, recommendations_path(recipient: recommendable, book: user_book), method: :post, role: 'menuitem', tabindex: '-1') %> </li>
                <% end %>
              </ul>
            </div> </div>

            <% end %> </div>
            <div class="col-md-1">
            <div class="btn-group-vertical">

              <% if current_user.listed_book_from_book(user_book).order_index > 0 %>
                <%= link_to listed_book_path(current_user.listed_book_from_book(user_book), move: :up), method: :patch, class: 'btn btn-default btn-sm'  do %> <span class="glyphicon glyphicon-chevron-up"></span> <% end %> <% end %>
                <% unless current_user.last_listed_book?(current_user.listed_book_from_book(user_book)) %>
                <%= link_to listed_book_path(current_user.listed_book_from_book(user_book), move: :down), method: :patch, class: 'btn btn-default btn-sm'  do %> <span class="glyphicon glyphicon-chevron-down"></span>
                <% end %> <% end %>
            </div>

        <% elsif !user_signed_in? %>
          <%= button_to "Add to MyReads", new_user_session_path, method: :get, class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<% if user_signed_in? && user == current_user %>
<!-- Popup itself. This is a form for comment but it will be going to the ListedBooks controller where the comment will be generated. Then the book will be marked as read. -->
<div id="test-popup" class="white-popup mfp-hide">

  <%= bootstrap_form_for Comment.new, url: listed_book_path(current_user.listed_book_from_book(user_book), is_read: true), method: :patch do |f| %>
    <%= f.text_field :content, hide_label: :true, placeholder: "Please leave a comment about the book..." %>
    <%= f.submit %>

  <% end %>
</div>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="text-center">Find A User</h2>
  </div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_tag users_path, method: 'get', role: "form" do%>
        <div class="input-group" style="padding-top: 20px;">
          <%= text_field_tag :search_user, params[:search_user], class: "form-control", placeholder: "Find A User" %>
          <span class="input-group-btn">
            <%= submit_tag "Go!", name: nil, class: "btn btn-default" %>
          </span>
        </div>
      <% end %>
  </div>
</div>

<% if @users.present? %>
  <div class="spacer50"> </div>
  <%= render partial: "user", collection: @users %>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1 class="text-center"><%= @user == current_user ? "Your Reads" : @user.username + "'s Reads" %> </h1>
  </div>
  <div class="col-md-2">
    <% if user_signed_in? && current_user.followees.include?(@user) %>
      <div class="btn-group pull-right">
        <button type="button" class="btn btn-success btn-lg dropdown-toggle" data-toggle="dropdown">
          Following <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <% unless current_user.requested_user?(@user)%>
            <li><%= link_to("Request Follow", requests_path(recipient_id: @user), method: :post) unless @user.is_following?(current_user) %></li>
          <% else %>
            <li><%= link_to "Delete Request", request_delete_path(recipient_id: @user, user_id: current_user), method: :delete %> </li>
          <% end %>
          <li><%= link_to("Unfollow", user_follow_path(followee_id: @user.id), method: :delete)  %></li>
        </ul>
      </div>
    <% elsif user_signed_in? && @user != current_user %>
      <%= button_to("Follow", user_follows_path(@user), class: 'btn btn-primary btn-lg pull-right')  %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <ul class="nav nav-tabs" role="tablist" id="myTab">
      <li class="active wantthisblack"><a href="#unread" role="tab" data-toggle="tab">ToReads</a></li>
      <li><a href="#read" class="wantthisblack" role="tab" data-toggle="tab">HaveReads</a></li>
    </ul>
  </div>
</div>


<div class="tab-content">
  <div class="tab-pane active" id="unread">
    <% @user_unread_books.each do |user_book, recommendables| %>
      <%= render partial: "user_book", locals: { user_book: user_book, recommendables: recommendables, has_read: false, user: @user } %>
    <% end %>
  </div>

  <div class="tab-pane" id="read">
    <% @user_read_books.each do |user_book, recommendables| %>
      <%= render partial: "user_book", locals: { user_book: user_book, recommendables: recommendables, has_read: true, user: @user } %>
    <% end %>
  </div>
</div>