config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only: [:index , :show] do
    resources :comments, only: [:destroy, :create]
  end
  resources :users, only: [:index, :show] do
    resources :follows, only: [:create]
  end

  resources :requests, only: [:create, :index]
  resources :listed_books, only: [:create, :update]
  resources :recommendations, only: [:create]

  #get 'books/:asin', to: 'books#show'
  delete 'follows', to: 'follows#destroy', as: 'user_follow'
  #post 'books/comments/:asin', to: 'comments#create', as: 'books_comment'
  delete 'requests', to: 'requests#destroy', as: 'request_delete'
  delete 'recommendations', to: 'recommendations#destroy', as: 'recommendation_delete'
  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :contributions, dependent: :destroy
  has_many :authors, through: :contributions

  validates :title, :asin, presence: true

  NO_IMAGE = "http://g-ecx.images-amazon.com/images/G/01/x-site/icons/no-img-lg._V192198896_BO1,204,203,200_.gif"

  def self.top_ten(user)
    unless user.present?
      #gets most commented books for the homepage
      self.all.to_a.sort! { |a,b| a.comments.size <=> b.comments.size}.reverse[0..9]
    else
      #gets the most recently commented books by the people that the user is following
      comments = []
      user.followees.each { |user| comments += user.comments}
      comments.to_a.sort_by(&:created_at).reverse.map(&:book).uniq
    end
  end

  def most_recent_comment(user)
    unless user.present?
      self.comments.includes(:user).order(:created_at).last
    else
      comments = []
      user.followees.each { |user| comments += user.comments}
      comments.select { |comment| comment.book == self }.sort_by(&:created_at).first
    end
  end

  def self.from_amazon_element(element)

    as_a_book = Book.new(
      photo: element.get_hash('MediumImage') ? element.get_hash('MediumImage')['URL'] : NO_IMAGE,
      title: element.get('ItemAttributes/Title'),
      published_on: element.get('ItemAttributes/PublicationDate'),
      asin: element.get('ASIN'),
      large_photo: element.get_hash('LargeImage') ? element.get_hash('LargeImage')['URL'] : NO_IMAGE
    )

    authors = element.get_element('ItemAttributes').get_array('Author')
    authors.each do |author|
      as_a_book.authors. << Author.get_author(author)
    end

    as_a_book
  end

  def self.search(search, search_method, user)
    if search

      books = []
      res = Amazon::Ecs.item_search('', {:response_group => 'Medium', search_method.downcase.to_sym => search})
      res.items.each do |item|

        books << Book.from_amazon_element(item)
      end
      books
    else
      self.top_ten(user)
    end
  end

  def self.get_book(asin)

    book = Book.from_amazon_element(
      Amazon::Ecs.item_lookup(asin,
      {:response_group => 'Medium'}).items.first) unless
        (book = Book.find_by(asin: asin)).present?

    book
  end

  #This almost never works because Amazon.
  def self.top_sellers
    books = []
    res = Amazon::Ecs.browse_node_lookup('1000', {:response_group => 'TopSellers'})
    doc = Nokogiri::XML(res.doc.children.to_s)
    asins = doc.xpath("//ASIN")
    asins = asins.map(&:text)[0..9]
    asins.each do |asin|
      books << Book.from_amazon_element(Amazon::Ecs.item_lookup(asin, :response_group => "Medium").items.first)
    end
    books
  end

  def to_param
    self.asin
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.includes(:authors).search(params[:search], params[:search_method], current_user)
    unless @books.present?
      #@books = Book.top_sellers
      flash[:notice] = "Amazon's Best Sellers. Please follow more users to see individulaized results."
    end

  end

  def show
    @book = Book.get_book(params[:id])
    @book.comments.includes(:user)
    @comment = Comment.new
  end
end

app/views/books/_book.html.erb
<div class="row">
  <div class="panel panel-default">
    <div class="panel-body book">
      <div class="col-md-3">
        <%= image_tag(book.photo, class: "img-responsive", alt: "Responsive image") %>
      </div>
      <div class="col-md-6">
        <h4> <%= link_to book.title, book_path(book) %> </h4> <br>
        <h5>By: <%= book.authors.map(&:name).join(', ') %></h5> <br>
        <% if (@comment = book.most_recent_comment(current_user)).present? %>

          <!-- I pass in the current user here so that it will only show comments
          from users that the current user is following -->

          <%= @comment.content %> says <%= link_to @comment.user.username, @comment.user %>
        <% end %>
        <%= "Recommended by: #{recommender.username}" if defined?(recommender).present? %>

      </div>
      <div class="col-md-3">
        <% if defined?(recommender).present? %> <div class="btn-group"> <% end %>
        <%= link_to "Add to MyReads", listed_books_path(asin: book.asin), method: :post, class: "btn btn-success" if user_signed_in? && current_user.does_not_have(book) %>
        <%= button_to "Add to MyReads", new_user_session_path, method: :get, class: "btn btn-success" unless user_signed_in? %>
        <%= link_to "Ignore request", recommendation_delete_path(user: recommender, recipient: current_user, book: book), method: :delete, class: "btn btn-danger" if defined?(recommender).present? %>
        <% if defined?(recommender).present? %> </div> <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/_comment.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default comment">
      <div class="panel-body">
        <%= comment.content %>
      </div>
      <div class="panel-footer">
        Says <%= comment.user.username %> on <%= comment.created_at %>
        <% if current_user == comment.user %>
          <%= link_to book_comment_path(comment.book, comment), method: :delete, class: "btn btn-danger btn-sm pull-right", style: "margin-top: -5px;" do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          <%end %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render partial: "book", collection: @books %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag(@book.large_photo, class: "img-responsive text-left", alt: "Responsive image", style: "margin-left: -95px;") %>
  </div>
  <div class="col-md-9">
    <h1 class="text-center"><%= @book.title %></h1> <br>
    <h2 class="text-center"><%= @book.authors.map(&:name).join(', ') %></h2> <br>
    <h4 class="text-center"><%= @book.published_on %></h4>
  </div>
</div>

<div class="row">
  <h3 class="text-center">Comments</h3>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <%= form_for @comment, url: book_comments_path(@book) do |f| %>
        <%= f.text_area :content, class: "form-control", placeholder: "Post a Comment" %>
         <div class="panel-footer">
          <%= f.button class: 'btn btn-success' do %>
            <span class="glyphicon glyphicon-ok"></span> Post
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render partial: "comment", collection: @book.comments %>