config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only: [:index , :show] do
    resources :comments, only: [:destroy, :create]
  end
  resources :users, only: [:index, :show] do
    resources :follows, only: [:create]
  end

  resources :requests, only: [:create, :index]
  resources :listed_books, only: [:create, :update]
  resources :recommendations, only: [:create]

  #get 'books/:asin', to: 'books#show'
  delete 'follows', to: 'follows#destroy', as: 'user_follow'
  #post 'books/comments/:asin', to: 'comments#create', as: 'books_comment'
  delete 'requests', to: 'requests#destroy', as: 'request_delete'
  delete 'recommendations', to: 'recommendations#destroy', as: 'recommendation_delete'
  root 'books#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>MyReads</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyReads", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to 'Find User', users_path %> </li>

      </ul>
      <%= form_tag books_path, method: 'get', class: "navbar-form navbar-left", role: "search" do%>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>
          <%= select_tag :search_method, "<option>Title</option><option>Author</option>".html_safe, class: "form-control" %>
        </div>
        <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><strong><% if user_signed_in? && (@num_reqs = current_user.inverse_requests.count + current_user.inverse_recommendations.count) > 0 %><span class="badge"><%= @num_reqs %></span> <% end %> <%= user_signed_in? ? current_user.username : "Profile" %> <span class="caret"></span></strong></a>
          <ul class="dropdown-menu" role="menu">
            <% if user_signed_in? %>
              <li><%= link_to 'Edit profile', edit_user_registration_path %> </li>
              <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %> </li>
              <li> <%= link_to "Login", new_user_session_path %> </li>
            <% end %>

            <li class="divider"></li>
            <li><%= link_to "ToRead", user_path(current_user) if user_signed_in?%></li>
            <li><%= link_to "ToRead", new_user_session_path unless user_signed_in?%></li>
            <li><%= link_to "MyReaders", users_path(only_follow: true) if user_signed_in?%></li>
            <li><%= link_to "MyReaders", new_user_session_path unless user_signed_in?%></li>
            <li><%= link_to "MyMessages", requests_path if user_signed_in?%></li>
            <li><%= link_to "MyMessages", new_user_session_path unless user_signed_in?%></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
 <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <%= bootstrap_flash %>
    </div>
  </div>
  <%= yield %>
</div>

</body>
<%= javascript_include_tag "myreads" %>
</html>